packages:
  - cascadia-code-fonts
  - curl
  - git
  - gpg
  - htop
  - wget
  - yakuake

flatpaks:
  - com.bitwarden.desktop
  - org.flameshot.Flameshot
  - org.gnome.Extensions
  - org.mozilla.Thunderbird
  - org.signal.Signal
  - com.spotify.Client

ssh_rsa:
  create: true
  password: "<password>"
  comment: "<comment>"

ssh_ed25519:
  create: true
  password: "<password>"
  comment: "<comment>"