---
packages:
  - bash-completion
  - curl
  - flatpak
  - git
  - gpg
  - htop
  - jq
  - vim
  - wget
  - yakuake

flatpaks:
  - com.bitwarden.desktop
  - org.flameshot.Flameshot
  - org.gnome.Extensions
  - org.mozilla.Thunderbird
  - org.signal.Signal
  - com.spotify.Client

# TODO: generate or import ssh keys and combine both
ssh_rsa:
  create: false
  password: "<password>"
  comment: "<comment>"

ssh_ed25519:
  create: false
  password: "<password>"
  comment: "<comment>"

bashrc:
  enabled: true
  additional_content: |
    parse_git_branch() {
      git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
    }
    export PS1='\[\e[0;1;38;5;34m\]\u\[\e[0;1;38;5;34m\]@\[\e[0;1;38;5;34m\]\h\[\e[0;1m\]:\[\e[0;1;38;5;33m\]\w \[\e[0;91m\]$(parse_git_branch)\[\e[0m\]\$ \[\e[0m\]'
    source <(kubectl completion bash)
    alias k=kubectl
    complete -o default -F __start_kubectl k

git_config:
  - setting: "user.name"
    scope: "global"
    value: "$full_name"
  - setting: "user.email"
    scope: "global"
    value: "$email"
  - setting: "pull.rebase"
    scope: "global"
    value: "false" # set to merge
  - setting: "push.autoSetupRemote"
    scope: "global"
    value: "true"
