packages:
  - wget
  - gpg
  - git
  - curl
  - htop
  - cascadia-code-fonts

flatpaks:
  - com.spotify.Client
  - org.gnome.Extensions
  - com.bitwarden.desktop
  - org.signal.Signal
  - org.mozilla.Thunderbird

ssh_rsa:
  password: "<password>"
  comment: "<comment>"

ssh_ed25519:
  password: "<password>"
  comment: "<comment>"