---
- name: "Initial Client Setup"
  hosts: localhost 
  become: true
  tasks:
  - name: Install packages
    package:
      name: 
      - wget
      - gpg
      - git
      state: present

  - name: Import VSCode key on RedHat based Linux
    rpm:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Import VSCode key on RedHat based Linux
    shell:
      cmd: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install VSCode on Debian based Linux
    get_url:
      url: https://go.microsoft.com/fwlink/?LinkID=760868
    when: ansible_facts['os_family'] == "Debian"



    