---
- name: "Add repository for Kubectl (RedHat)"
  ansible.builtin.yum_repository:
    name: "kubernetes"
    description: "Kubernetes Stable"
    baseurl: "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/"
    gpgkey: "https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key"
    gpgcheck: true
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"

- name: "Add repository for Hashicorp (RedHat)"
  ansible.builtin.yum_repository:
    name: "hashicorp"
    description: "Hashicorp Stable - $basearch"
    baseurl: "https://rpm.releases.hashicorp.com/{{ ansible_facts['distribution'] | lower }}/$releasever/$basearch/stab\
             le"
    gpgkey: "https://rpm.releases.hashicorp.com/gpg"
    gpgcheck: true
    enabled: true
  when: ansible_facts['os_family'] == "RedHat"

- name: "Update cache for RedHat based distributions"
  ansible.builtin.yum:
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"

- name: "Add repository for kubectl (Debian)"
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Add an Apt signing key to a specific keyring file
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: "Add kubectl repo"
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb\
              / /"
        filename: "kubernetes"

- name: "Add repository for Hashicorp (Debian)"
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: "Download hashicorp gpg key"
      ansible.builtin.get_url:
        url: "https://apt.releases.hashicorp.com/gpg"
        dest: "/usr/share/keyrings/hashicorp-archive-keyring"
        mode: "0644"

    - name: "Unpack hashicorp gpg key"
      ansible.builtin.command: >
       sudo gpg --dearmor /usr/share/keyrings/hashicorp-archive-keyring
      changed_when: false

    - name: "Change File Mod gpg"
      ansible.builtin.file:
        path: "/usr/share/keyrings/hashicorp-archive-keyring"
        mode: "0644"

    - name: "Add hashicorp repo"
      ansible.builtin.copy:
        content: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
                 https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
        dest: "/etc/apt/sources.list.d/hashicorp.list"
        mode: "0644"

- name: "Update cache for Debian based distributions"
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: "Install kubectl and terraform"
  ansible.builtin.package:
    name:
      - "kubectl"
      - "terraform"
    state: "present"

- name: "Install Ansible-lint"
  ansible.builtin.pip:
    name: "ansible-lint"

- name: "Helm installation"
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: "Download Helm"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
        dest: "/tmp/get_helm.sh"
        mode: "0700"

    - name: "Install Helm"
      ansible.builtin.command:
        cmd: "/tmp/get_helm.sh"
      register: install_helm
      changed_when: false

- name: "Add repository for Hashicorp (Debian)"
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: "Get latest release of k9s"
      ansible.builtin.uri:
        url: "https://api.github.com/repos/derailed/k9s/releases/latest"
        return_content: true
      register: k9s_github_download_link

    - name: "Set download URL"
      ansible.builtin.set_fact:
        github_download_url:
          "{{ (k9s_github_download_link.json.assets | selectattr('browser_download_url', 'contains', k9s_Linux_amd64) |\
          first).browser_download_url }}"

    - name: "Install k9s"
      ansible.builtin.unarchive:
        src: "{{ github_download_url }}"
        remote_src: true
        include: "k9s"
        dest: "/usr/local/bin"
        group: "root"
        owner: "root"
        mode: "0755"
