- name: Include vars
  include_vars: 
    file: ./configuration.yml

- name: Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

- name: Install redhat based packages
  become: true
  package:
    name: 
    - podman
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Import VSCode key on RedHat based Linux
  become: true
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Import VSCode key on RedHat based Linux
  become: true
  command:
    cmd: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
  when: ansible_facts['os_family'] == "RedHat"

- name: Install VSCode on Debian based Linux
  become: true
  get_url:
    url: https://go.microsoft.com/fwlink/?LinkID=760868
  when: ansible_facts['os_family'] == "Debian"

- name: Install {{ item }}
  community.general.flatpak: 
    name: "{{ item }}"
    state: present
  loop: "{{ flatpaks }}"
