- name: Include vars
  include_vars: 
    file: ./configuration.yml
    
- name: Update all packages to the lastest state
  become: true
  package:
      name: "*"
      state: latest

- name: "Initialze flathub"
  command:
    cmd: "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
  when: ansible_facts['os_family'] == "RedHat"
  
- name: Add content to .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      parse_git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
      }
      export PS1='\[\e[0;1;38;5;34m\]\u\[\e[0;1;38;5;34m\]@\[\e[0;1;38;5;34m\]\h\[\e[0;1m\]:\[\e[0;1;38;5;33m\]\w \[\e[0;91m\]$(parse_git_branch)\[\e[0m\]\$ \[\e[0m\]'

- name: Generate an RSA OpenSSH keypair 
  community.crypto.openssh_keypair:
    type: rsa 
    size: 4096
    comment: "{{ ssh_rsa.comment }}"
    passphrase: "{{ ssh_rsa.password }}"    
    path: ~/.ssh/id_rsa
  when: ssh_rsa.create == true

- name: Generate an ed25519 OpenSSH keypair
  community.crypto.openssh_keypair:
    type: ed25519 
    comment: "{{ ssh_ed25519.comment }}"
    passphrase: "{{ ssh_ed25519.password }}"
    path: ~/.ssh/id_ed25519
  when: ssh_ed25519.create == true 
