---
- name: "Include vars"
  ansible.builtin.include_vars:
    file: "./configuration.yml"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  loop: "{{ packages }}"

- name: "Add rpmfustion repo gpg keys"
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items: 
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
  when: ansible_facts['distribution'] == "Fedora"

- name: "install the rpmfusion repo packages"
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when: ansible_facts['distribution'] == "Fedora"

- name: "Install redhat based packages"
  ansible.builtin.dnf:
    name:
      - "cascadia-code-fonts"
      - "ffmpeg-libs"
      - "podman"
    state: "present"
    allowerasing: true
  when: ansible_facts['os_family'] == "RedHat"

- name: "Install Debian based packages"
  ansible.builtin.apt:
    name:
      - "ffmpeg"
      - "fonts-cascadia-code"
    state: "present"
  when: ansible_facts['os_family'] == "Debian"

- name: "Import and install VSCode on RedHat based Linux systems"
  when: ansible_facts['os_family'] == "RedHat"
  block:
    - name: "Import VSCode key on RedHat based Linux"
      ansible.builtin.yum_repository:
        name: "vscode"
        description: "Visual Studio Code"
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        gpgcheck: true
        enabled: true

    - name: "Install VSCode on RedHat based Linux"
      ansible.builtin.yum:
        name: "code"
        state: "present"

- name: "Check if vscode is installed"
  ansible.builtin.stat:
    path: "/usr/bin/code"
  register: check_vs_code_installation

- name: "Install VSCode on Debian based Linux"
  ansible.builtin.apt:
    deb: "https://go.microsoft.com/fwlink/?LinkID=760868"
  when: ansible_facts['os_family'] == "Debian" and check_vs_code_installation.stat.exists

- name: "Add flahub repository"
  community.general.flatpak_remote:
    name: "flathub"
    state: "present"
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    method: "system"

- name: "Install flatpak packages"
  community.general.flatpak:
    name: "{{ item }}"
    state: "present"
    method: "system"
  loop: "{{ flatpaks }}"
