---
- name: "Include vars"
  ansible.builtin.include_vars:
    file: "./configuration.yml"

- name: "Install packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "present"
  loop: "{{ packages }}"

- name: Enable the RPM Fusion repository
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}\
           .noarch.rpm"
    state: present
  when: ansible_distribution == 'Fedora'

- name: "Install redhat based packages"
  ansible.builtin.package:
    name:
      - "cascadia-code-fonts"
      - "ffmpeg-libs"
      - "podman"
    state: "present"
  when: ansible_facts['os_family'] == "RedHat"

- name: "Install redhat based packages"
  ansible.builtin.package:
    name:
      - "ffmpeg"
      - "fonts-cascadia-code"
    state: "present"
  when: ansible_facts['os_family'] == "Debian"

- name: "Import and install VSCode on RedHat based Linux systems"
  when: ansible_facts['os_family'] == "RedHat"
  block:
    - name: "Import VSCode key on RedHat based Linux"
      ansible.builtin.yum_repository:
        name: "vscode"
        description: "Visual Studio Code"
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
        gpgcheck: true
        enabled: true

    - name: "Install VSCode on RedHat based Linux"
      ansible.builtin.yum:
        name: "code"
        state: "present"

- name: "Install VSCode on Debian based Linux"
  ansible.builtin.apt:
    deb: "https://go.microsoft.com/fwlink/?LinkID=760868"
  when: ansible_facts['os_family'] == "Debian"

- name: "Add flahub repository"
  community.general.flatpak_remote:
    name: "flathub"
    state: "present"
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    method: "user"

- name: "Initialize flathub"
  community.general.flatpak_remote:
    name: "flathub"
    state: "present"
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    method: "user"

- name: "Install flatpak packages"
  community.general.flatpak:
    name: "{{ item }}"
    state: "present"
    method: "user"
  loop: "{{ flatpaks }}"
